### ISSUE TITLE
Classification custom labels

### ISSUE THREAD

**Issue by TTErallye** [stdp/akida-camera#1]
How would i /what do i need to do to ..... give each class a meaningful descriptive label when learning a new object? 

Great work, thanks, trying to learn... Cheers, JJ

**Comment by stdp** [comment]
Hi - You could create a dict of labels, eg.

`LABELS = {
    0: "Background",
    1: "Example 1",
}`

**Comment by TTErallye** [comment]
so much to learn!!!  , Also Thank you for your quick and helpful response, will have a play today, I worked out how to change the colors and screen position of the frame labels last night,   but thats nothing in the big picture.  Haha

Update:  I still have no idea what I'm doing, dang....well, time to do some/continue googling.
